### PR TITLE
Deps: Less strict json version

### PR DESCRIPTION
**Pull request by TobiasRoikjer**

### CODE REVIEW

**Comment by jmoody** [comment]
Maybe ">= 1.8", "< 3.0"?  Otherwise this is fine.

**Comment by TobiasRoikjer** [comment]
@jmoody Your call. I don't think it is necessary

**Comment by jmoody** [comment]
Let's keep it less restrictive across all the tools.  If we have a problem later, we can be more restrictive.  Thanks for handling this!

**Comment by TobiasRoikjer** [comment]
That sounds like a good idea. From my immediate tests json 2.0.2 seems to work fine

**Pull request closed without merging**
